routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\UserFollowsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PagesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostsController::class, 'index'])->name('home')->middleware(['auth']);

Route::resource('posts', PostsController::class)->middleware(['auth']);

Route::resource('posts.comments', CommentsController::class)
    ->only(
        [
            'store', 'update',
        ]
    )->middleware(['auth']);
Route::resource('users.follows', CommentsController::class)->middleware(['auth']);
Route::resource('comments', CommentsController::class)->middleware(['auth']);
Route::resource('pages', PagesController::class)->middleware(['auth']);
Route::resource('users', UsersController::class)->middleware(['auth']);
Route::resource('follows', UserFollowsController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::post('follows/{follow}', [UserFollowsController::class, 'destroy']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware(['auth']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return HasMany
     */
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function followers(): BelongsToMany
    {
        return $this->BelongsToMany(User::class, 'user_follow', 'follower_id', 'follow_id');
    }

    /**
     * @return BelongsToMany
     */
    public function follows(): BelongsToMany
    {
        return $this->BelongsToMany(User::class, 'user_follow', 'follower_id', 'follow_id');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Follow;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')


@section('content')

    <div style="padding-bottom: 30px;">
        <h1>All users</h1>
    </div>

    <table class="table" style="padding-top: 30px">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            @if(Auth::user()->id != $user->id)
                <tr>
                    <td>
                        {{$user->name}}
                    </td>
                    <td>
                        @if((\App\Models\Follow::where('follow_id', '=', $user->id)->exists() && \App\Models\Follow::where('follower_id', '=', Auth::user()->id)->exists()) !== true)
                        <form method="post" action="{{route('follows.store')}}">
                            <input name="follow_id" type="hidden" id="follow_id" value="{{$user->id}}">
                            @csrf
                            <button type="submit" class="btn btn-success">Follow</button>
                        </form>
                        @elseif((\App\Models\Follow::where('follow_id', '=', $user->id)->exists() && \App\Models\Follow::where('follower_id', '=', Auth::user()->id)->exists()) === true)
                            <form method="post" action="{{route('follows.destroy', ['follow' => $user])}}">
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-danger">Unfollow</button>
                            </form>
                            @endif
                            @else

                        @endif
                    </td>
                </tr>
        @endforeach
        </tbody>
    </table>

@endsection