routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\UserFollowsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PagesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostsController::class, 'index'])->name('home')->middleware(['auth']);

Route::resource('posts', PostsController::class)->middleware(['auth']);

Route::resource('posts.comments', CommentsController::class)
    ->only(
        [
            'store', 'update',
        ]
    )->middleware(['auth']);
Route::resource('users.follows', CommentsController::class)->middleware(['auth']);
Route::resource('comments', CommentsController::class)->middleware(['auth']);
Route::resource('pages', PagesController::class)->middleware(['auth']);
Route::resource('users', UsersController::class)->middleware(['auth']);
Route::resource('follows', UserFollowsController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::post('follows/{follow}', [UserFollowsController::class, 'destroy']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware(['auth']);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['picture', 'body', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function likes(): HasMany
    {
        return $this->hasMany(Like::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Form\PostForm;
use App\Http\Requests\PostRequest;
use App\Models\Follow;
use App\Models\Post;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $allPosts = Post::all();
        $follows = Follow::where('follower_id', auth()->user()->id)->get();
        $posts = [];
        foreach ($allPosts as $post) {
            foreach ($follows as $follow) {
                if ($post->user_id == $follow->follow_id) {
                    $posts[] = $post;
                }
            }
        }
        return view('posts.index', compact('posts'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * @param PostRequest $request
     * @return RedirectResponse
     */
    public function store(PostRequest $request): RedirectResponse
    {
        $post = PostForm::execute($request);
        $post->user()->associate($request->user());
        $post->save();
        return redirect()->route('posts.index')->with('status', "Post successfully created!");
    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    public function destroy(Post $post): RedirectResponse
    {
        $post->delete();
        return redirect()->route('posts.index')->with('status', "Post successfully deleted!");
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create post</h1>
    <form enctype="multipart/form-data" method="post" action="{{ route('posts.store') }}">
        @csrf
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body"
                      name="body"></textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('picture') is-invalid @enderror" id="customFile"
                       name="picture" value="picture">
                @error('picture')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <h2 class="pt-md-5">Posts of users that you are following:</h2>
    <a href="{{route('posts.create')}}" type="button" class="btn btn-outline-primary">
        Add post
    </a>
    <div class="row">
        @foreach($posts as $post)
            <div class="card m-3" style="width: 18rem;">
                <img src="{{asset('/storage/' . $post->picture)}}" class="card-img-top"
                     style="height: 290px; width: auto" alt="{{asset('/storage/' . $post->picture)}}"
                     width="50px" height="50px">
                <div class="card-body">
                    <p>{{$post->likes->count()}} Likes</p>
                    <strong>Author: {{$post->user->name}}</strong>
                    <p>{{$post->body}}</p>
                    @can('delete', $post)
                        <form method="post" action="{{route('posts.destroy', ['post' => $post])}}">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    @endcan
                    @can('like', $post)
                    <form method="post" action="{{route('likes.store')}}">
                        <input name="post_id" type="hidden" id="post_id" value="{{$post->id}}">
                        @csrf
                        <button type="submit" class="btn btn-success">Like</button>
                    </form>
                        @endcan
                        <a href="{{route('posts.show', ['post' => $post])}}" class="btn btn-primary">More</a>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="border-bottom pb-3 mb-3">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 .img-fluid. w-100%  h-auto ">
                <div class="col mb-4">
                    <br>
                    <h4>Post:</h4>
                    @if (!is_null($post->body))
                        <p>{{$post->body}}</p>
                    @else
                        Нет описания
                    @endif
                </div>
                <div class="col mb-1 ">
                    <img src="{{asset('/storage/' . $post->picture)}}"
                         class="rounded mx-auto d-block img-fluid rounded float-right"
                         alt="{{asset('/storage/' . $post->picture)}}" width="200px" height="200px">
                </div>
                <footer class="blockquote-footer">
                    Author: {{$post->user->name}}, created in
                </footer>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>Comments</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-8 scrollit">
                @foreach($post->comments as $comment)
                    @include('comments.comment', ['comment' => $comment])
                @endforeach
            </div>
            <div class="col-4 fixed">
                <div class="comment-form">
                    <form id="create-comment">
                        @csrf
                        <input type="hidden" id="post_id" value="{{$post->id}}">
                        <div class="form-group">
                            <label for="commentFormControl">Comment</label>
                            <textarea name="body" class="form-control" id="commentFormControl" rows="3"
                                      required></textarea>
                        </div>
                        <button id="create-comment-btn" type="submit" class="btn btn-outline-primary btn-sm btn-block">
                            Add new
                            comment
                        </button>
                    </form>
                </div>
            </div>
        </div>
@endsection