routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\UserFollowsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\PagesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostsController::class, 'index'])->name('home')->middleware(['auth']);

Route::resource('posts', PostsController::class)->middleware(['auth']);

Route::resource('posts.comments', CommentsController::class)
    ->only(
        [
            'store', 'update',
        ]
    )->middleware(['auth']);
Route::resource('users.follows', CommentsController::class)->middleware(['auth']);
Route::resource('comments', CommentsController::class)->middleware(['auth']);
Route::resource('pages', PagesController::class)->middleware(['auth']);
Route::resource('users', UsersController::class)->middleware(['auth']);
Route::resource('follows', UserFollowsController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::resource('likes', LikesController::class)->middleware(['auth']);
Route::post('follows/{follow}', [UserFollowsController::class, 'destroy']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware(['auth']);

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
    <h2 class="pt-md-5">Posts:</h2>
    @can('create', \App\Models\Post::class)
        <a href="{{route('posts.create')}}" type="button" class="btn btn-outline-primary">
            Add post
        </a>
    @endcan
    <div class="row">
        @foreach($posts as $post)
            <div class="card m-3" style="width: 18rem;">
                <img src="{{asset('/storage/' . $post->picture)}}" class="card-img-top"
                     style="height: 290px; width: auto" alt="{{asset('/storage/' . $post->picture)}}"
                     width="50px" height="50px">
                <div class="card-body">
                    <p>{{$post->likes->count()}} Likes</p>
                    <strong>Author: {{$post->user->name}}</strong>
                    <p>{{$post->body}}</p>
                    @can('delete', $post)
                        <form method="post" action="{{route('posts.destroy', ['post' => $post])}}">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-danger">Delete</button>
                            @endcan
                        </form>
                        <a href="{{route('posts.show', ['post' => $post])}}" class="btn btn-primary">More</a>
                </div>
            </div>
        @endforeach
    </div>
@endsection